Internship_2/Internship_2/Controllers/SellController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Internship_2.Controllers
{
    public class SellController : Controller
    {
        // GET: Sell
        public ActionResult Index()
        {
            return View();
        }
    }
}

Internship_2/Internship_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
            <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css">
            @Styles.Render("~/Content/css")

 
            <div class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color:#3982ac">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" ng-click="navbarProperties.isCollapsed = !navbarProperties.isCollapsed">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>                       
                    </div>
                    <div class="navbar-collapse collapse" collapse="navbarProperties.isCollapsed">
                        <ul class="nav navbar-nav">
                            <li><div class="text">@Html.ActionLink("LOGO","Index","Home")</div></li>                  <!--Insert Logo Image here-->
                            <li>+91 7259 28 0001</li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><div class="text">@Html.ActionLink("About Us","AboutUs","Home")</div></li>
                            <li><div class="text">@Html.ActionLink("How It Works", "HowItWorks", "Home")</div></li>
                            <li><div class="text">@Html.ActionLink("Login", "Login", "Account")</div></li>
                            <li><div class="text" style="padding-right:10px;">@Html.ActionLink("Buy", "Index", "Buy")</div></li>
                            <li>
                            <form action="/Sell/Index">
                                <input type="submit" value="Sell Your Car" class="myButton" />
                                </form>
                            </li> 
                        </ul>
                    </div>
                </div>
            </div>

    </header>
   
    

        @RenderBody()
        <hr />
        <div style="background-color:#4682B4">
            <footer style="width:100%;height:250px; color:white">
                <div style="float: left; width: 25%;">
                    <ul style="list-style-type:none">
                        <li style="padding-bottom:10px"><h3>Overview</h3></li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Press", "Press", "Home")</li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Sell A Car", "Index", "Sell")</li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Buy A Car", "Index", "Buy")</li>

                    </ul>
                </div>
                <div style="float: left; width: 25%;">
                    <ul style="list-style-type:none">
                        <li style="padding-bottom:10px"><h3>DriveOJoy</h3></li>
                        <li style="padding-bottom:10px">@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Jobs", "Jobs", "Home")</li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Blog", "Blog", "Home")</li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home")</li>

                    </ul>
                </div>
                <div style="float: left; width: 25%;">
                    <ul style="list-style-type:none">
                        
                        <li style="padding-bottom:10px"><h3>Support</h3></li>
                        <li style="padding-bottom:10px">@Html.ActionLink("Contact Us", "ContactUs", "Home")</li>
                        <li style ="padding-bottom:10px">Call+91 7259280001</li>

                    </ul>
                </div>
                <div style="float: right; width: 25%; padding-top:50px;">
                    <ul style="list-style-type:none">
                        <li style="padding-bottom:10px"><a href="https://support@driveojoy.com/">https://support@driveojoy.com/</a></li>
                        <li style="padding-bottom:10px"><a href="https://www.facebook.com/driveojoy">https://www.facebook.com/driveojoy</a></li>
                        <li style="padding-bottom:10px"><a href="https://twitter.com/driveojoy">https://twitter.com/driveojoy</a></li>
                        <li style="padding-bottom:10px"><a href="https://www.linkedin.com/driveojoy">https://www.linkedin.com/driveojoy</a></li>
                        <li style="padding-bottom:10px"><a href="https://plus.google.com/driveojoy">https://plus.google.com/driveojoy</a></li>
                    </ul>
                </div>
            </footer>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>